apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contratos-api
  namespace: contratos
spec:
  ingressClassName: nginx
  rules:
    - host: contratos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contratos-api
                port:
                  number: 80
